Import('builder')

builder.library('reflection', 'REFLECTION_LIBRARY', Split(""), Split("""
classreflection.cpp
propertyreflection.cpp
reflectionregistry.cpp
reflectioncache.cpp
hierarchymanager.cpp
"""))
